acm:
  epoches: 200
  eva_epoches: 50
  num_layer: 2
  num_heads: 4
  num_out_heads: 1
  num_hidden: 1024
  lr: 0.0008
  mask_rate: 0.5
  dropout: 0.4
  encoder: "HAN"
  decoder: "HAN"
  weight_decay: 1e-4
  gamma: 3
